* Numpy Basics


In [10]:
import numpy as np
a = np.array([1,2,3])   ## vector  tenser
print(a*4)

[ 4  8 12]


In [25]:
a1 = np.full((3,4),"ali")
print(a1)

[['ali' 'ali' 'ali' 'ali']
 ['ali' 'ali' 'ali' 'ali']
 ['ali' 'ali' 'ali' 'ali']]


In [2]:
# create nupmy array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array:" , arr_1d)


1D array: [1 2 3 4 5]


In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D array:" , arr_2d)

2D array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
# list vs numpy
lst = [1, 2, 3, 4, 5]
print("List:", lst*3)


List: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
np_arr = np.array([1, 2, 3, 4, 5])
print("Numpy array:", np_arr*3)   ## element wise multiplication

Numpy array: [ 3  6  9 12 15]


In [12]:
import time 
start =time.time()
pytime = [i*2 for i in range(1000000)]
print("Time taken for list:", time.time()-start)

Time taken for list: 0.6819858551025391


In [17]:
start =time.time()
nptime = np.arange(1000000) *2
print("\n Time \n taken for numpy:", time.time()-start)


 Time 
 taken for numpy: 0.010110616683959961


In [3]:
#creating array from scratch
zeroarr = np.zeros((4, 3))
print("Zero array:\n", zeroarr)

Zero array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
zeroarr = np.ones((3, 3))
print("Zero array:\n", zeroarr)

Zero array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
full  = np.full ((3, 3),"hassan")
print("Full array:\n", full)
rand = np.random.random((3, 3))
print("Random array:\n", rand)
seq = np.arange(5, 20 , 3)
print("Sequence array:\n", seq)

Full array:
 [['hassan' 'hassan' 'hassan']
 ['hassan' 'hassan' 'hassan']
 ['hassan' 'hassan' 'hassan']]
Random array:
 [[0.4563045  0.69035738 0.6544237 ]
 [0.03724198 0.56555465 0.9343514 ]
 [0.02402782 0.47809615 0.10062891]]
Sequence array:
 [ 5  8 11 14 17]


### Vector Matrix Tensor

In [27]:
vector = np.array([1, 2, 3, 4, 5])
print("Vector:", vector) 

Vector: [1 2 3 4 5]


In [28]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:\n", matrix)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print("Tensor:\n", tensor)
# multi dimensional array 

Tensor:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


### Array proprty

In [27]:
arr = np.array([1, 2, 3, 4, 5])
print("Shape:", arr.shape)
print("Data type:", arr.dtype)
print("Size:", arr.size)
print("Dimension:", tensor.ndim)
print("Item size:", arr.itemsize)
print("Number of bytes:", arr.nbytes)
print("Strides:", arr.strides)
print("Flags:", arr.flags)
print("Contiguous array:", arr.flags.contiguous)
print("C array:", arr.flags.c_contiguous)
print("F array:", arr.flags.f_contiguous)

Shape: (5,)
Data type: int64
Size: 5
Dimension: 3
Item size: 8
Number of bytes: 40
Strides: (8,)
Flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

Contiguous array: True
C array: True
F array: True


### array reshaping

In [28]:
arr = np.arange(12)
print("Original array:", arr)
reshaped = arr.reshape(3, 4)
print("Reshaped array:\n", reshaped)
# flatten   (return copy)
flattened = reshaped.flatten()
print("Flattened array:", flattened)
# ravel (retrun view or orginal instead of copy)
raveled = reshaped.ravel()
print("Raveled array:", raveled)

#transpose
arr3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:\n", arr)
a = np.array([[1,2] , [2,3]])
ab = a.T
print("ahmad transpose:\n ", ab)
transposed = arr3.T
print("Original array transpose:\n ", transposed)





Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
ahmad transpose:
  [[1 2]
 [2 3]]
Original array transpose:
  [[1 4 7]
 [2 5 8]
 [3 6 9]]
